GET http://localhost:3110/api/users/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E1NDYwM2EyZTljODg2NWEyZDM0NTgiLCJpYXQiOjE3MzkyOTU1MDl9.xMOzzvvKDDW-t8FuKnv_wtO4zBmWFN0JK7cAamlnLUU



###
POST http://localhost:3110/api/genres
Content-Type: application/json




{
  "email": "aderomola@gmail.com",
  "password": "12345"
}
###
GET http://localhost:3110/api/genres

###
PATCH http://localhost:3110/api/movies/679359f23397c6d018e8c7f7
Content-Type: application/json

{
  "numberInStock": 25
}

###
DELETE http://localhost:3110/api/movies/67935a20ea41aebd493ca752